version: "3.7"

services:

    app:
        build:
          dockerfile: .docker/app/Dockerfile
          context: .
          target: dev
        container_name: cleanphp-app
        entrypoint: dockerize -template /templates/.env:.env -wait tcp://db:3306 -timeout 40s /entrypoint.sh
        volumes:
            - ./www:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: cleanphp-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./www:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: cleanphp-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: cleanphp-redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
